### ISSUE TITLE
Long Form TODO List

### ISSUE THREAD

**Issue by Ocelmot** [cowsed/PDMProject#12]
### Application Requirements

- [x] Users will be able to create new accounts and access via login. The system must record
the date and time an account is created. It must also store the dates and times users
access the application
- [x] Users will be able to create collections of video games.
- [x] #13 
The list must show the following information per collection:
    - [x] Collection’s name
    - [x] Number of video games in the collection
    - [x] Total play time of the video games (in hours:minutes) of video games in the
collection
- [x] #14
- [x] #16
Users should get a warning when adding a game to their collection for a platform that they do not own.
- [x] Users can modify the name of a collection. They can also delete an entire collection
- [x] #15
- [x] #17
- [x] Users can follow another user. Users can search for new users to follow by email
- [x] The application must also allow an user to unfollow a another user

### Submission Requirements

- [x] The report template will be updated to include:
    - [x] a current design phase section (if your ER or Reduction to tables changed, update
them)
    - [x] contains sample (2) SQL statements used to create your tables
    - [x] contains sample queries (2 for each table) for populating the data via your application
    - [x] contains a description of how the data was loaded into the database (was the
source manipulated, did you use a tool, etc) with 5 sample insert statements used
to initially populate data into the database
- [x] An EER Diagram (even if not updated).
- [x] Reduction to tables (even if not updated).
- [x] Large amount of data loaded into the postgres server that matches the reduction to
tables and the EER diagram, see below for what is considered a large amount of data.
See below for possible data sets that you can use.
- [x] Data in the database should be normalized to 3NF.
- [x] The source code of your application program (in a src folder). At this point, your
application must be able to perform all the operations stated in the Application
Requirements section of this phase.
- [x] A 6-10 minutes video demonstrating the application running and manipulating data
with a voice over explaining the application. You should show the database state
before and after the data changes to show how data is manipulated. We will not be
running your application, it is important that your demo covers the functionality of
the application.

### Additional Instructions
Data must be loaded into the proper account area.

Data in the dataset may have been converted to numbers for storage. (ie. 1 for male, 2 for
female). You must store them as their non-numeric values ( ie. male and female).

You must have enough data in this phase to do phase 4 and have it loaded for this phase.
How much is enough? 10s-100s of rows in each table, while a M:N table should have 200-500.
To simplify, after a join with a complex query, you should have several thousand rows.

Your application cannot be just a collection of ”select * from table” and have the apllication
combine the data. You must do the data and relationship combinations in SQL.

Submit a Zip file containing the report outlined above (Report.PDF), the ER Diagram
(ERDiagram.PDF), and a Reduction to tables (Reduction.PDF), a Video (Video.mov or
other type of movie file, no links) and your source files (inside a src folder) in a file name
Phase2.zip. All 3 PDF files should be in the root of the zip. Failure to follow any submission
guidelines (location of files, type of files, zipping, naming, etc) will earn a 0 for this phase.

You should update your peer evaluation for this phase at this time, though you are not
required to submit it at this time.

A 6-10 minutes video demonstrating the application running and manipulating data with
a voice over explaining the application. You should show the database state before and
after the data changes to show how data is manipulated (this can be done using a tool like
DataGrip). We will not be running your application, it is important that your demo covers
the functionality of the application.

There will be a penalty for going under or over the time for the video

**Comment by Ocelmot** [comment]
It might be nice to show a list of the players that one player follows

**Comment by Ocelmot** [comment]
I think it might have been worth it to check with the professors to see what it means by "See below for possible data sets that you can use." for our data sources. It looks like the next phase is to do analysis on the data, but our data is not very meaningful since it is synthetic.
