### ISSUE TITLE
Long Form TODO List

### ISSUE THREAD

**Issue by Ocelmot** [cowsed/PDMProject#27]
### Overview
For this phase, you must complete your application program including the recommendation
system and some extra functionalities. You must also perform some data analysis to discover
useful information.

### Application Requirements
- [x] #31 
- [x] #32
### Submission Requirements
- [ ] Final version of your application program. At this point, you application must include
all the functionalities stated above. Submit your source code (in a src folder)
- [ ] The report template will be updated to include:
    - [x] explaining the process/techniques used to analyze the data (what types of algorithms were used, did you use a tool for analytics, or did you create materialized views, etc)
    - [x] #36 explaining the indexes created to boost your application program’s performance
    - [x] containing an appendix listing all of the SQL statements used in this phase
    - [ ] complete the lessons learned section of the report
- [x] A poster showing:
    - [x] your team name
    - [x] the names of all team members
    - [x] the observations from the data analytics
    - [x] technologies used (Excel, Python, etc)
    - [x] visual representation of the data (charts, graphs, and other visual representations are required)
      _Designing an effective poster :_
        - include the team name and the name of all team members at the top
        - keep any text brief
        - do not use all capital letters
        - user graphics (charts, graphs, etc) that can be understood in one minute or less
        - add a descriptive caption below each figure; table heads should appear above
tables. Use the abbreviation (e.g. ”Fig. 1”) at the beginning of each caption.
That will make easier to refer to those figures during your poster presentation.
        - have 3 graphs/charts explaining the data with brief descriptions. These should
not be trivial. Two of these can be trivial charts or graphs, one must be complex
(getting data from at least 4 tables)
        - use color, sparingly. Find a color palette that works and is not distracting.
Poster must be easy to read and understand. The viewer should gain new knowledge or
insight by just looking over your poster. You can find a poster sample at myCourses.
You can also can take a look at the CS MS Capstone project’s posters. To access to
that information, you will need to login with your CS account.
- [ ] A single 7-10 minutes video that demonstrate the final version of your application and
presents your poster. Your video must be structured as follows:
    - [ ] Start by demonstrating the final version of your program. Make sure to demonstrate all functionalities defined in the Application Requirements from Phase 4. During the demonstration, you must show, from your source code, at least
two complex queries (e.g. multiple joins, nested queries, correlated queries) implemented during this phase. We will not be running your application. It is important that you demonstrate all the required functionality.
    - [ ] After that, you will present your poster.
        ∗ Familiarize viewers with the fundamentals of your program quickly and easily
        ∗ Use the information from your poster to present only the highlights
        ∗ Explain the patterns or conclusions drawn from the data analysis
    - [ ] There will be a penalty for going under or over the time for the video
